- name: check all packages deprecated
  yum:
    list: updates
  register: packages

- name: "check if '{{ package }}' is up to date"
  debug:
    msg: "'{{ package }}' is up to date"
  when: "'{{ package }}' not in packages.results | map(attribute='name') | list"

- name: "check if '{{ package }}' is deprecated"
  debug:
    msg: "'{{ package }}' is deprecated"
  when: "'{{ package }}' in packages.results | map(attribute='name') | list"

- name: Updating '{{ package }}'...
  yum:
    name: "{{ package }}"
    state: latest
  when: "{{ makeupdate }} and '{{ package }}' in packages.results | map(attribute='name') | list"

- name: check again all packages deprecated
  yum:
    list: updates
  register: packages
  when: "{{makeupdate}}"

- name: "check if '{{ package }}' has been updated"
  debug:
    msg: "'{{ package }}' has been updated"
  when: "{{makeupdate}} and '{{ package }}' not in packages.results | map(attribute='name') | list"